# Copyright (c) 2021 Arm Limited
# SPDX-License-Identifier: Apache-2.0

name: Active Update Push [ ci-build-env ]

on:
  # This workflow only runs when triggered by a push event
  push:
    # Only runs when take push events on master branch
    branches: [ main ]
    # Only runs take push changes Dockerfile inside ci-build-env folder
    paths:
      - 'ci-build-env/*/Dockerfile'

env:
  DOCKER_USER: mcudriverhal
  DOCKER_REPO: ci-build-env

jobs:

  TAG_sanity:
    runs-on: ubuntu-20.04
    env:
      TAG_NAME: sanity
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build image ${{env.DOCKER_REPO}}:${{env.TAG_NAME}}
      run: docker build ${{env.DOCKER_REPO}}/${{env.TAG_NAME}}/ --tag ${{env.DOCKER_REPO}}:${{env.TAG_NAME}}
    - name: Log in Docker Hub
      uses: docker/login-action@v1
      with:
        username: {{env.DOCKER_USER}}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push image tag <${{env.TAG_NAME}}> to remote
      run: |
        docker tag ${{env.DOCKER_REPO}}:${{env.TAG_NAME}} {{env.DOCKER_USER}}/${{env.DOCKER_REPO}}:${{env.TAG_NAME}}
        docker push {{env.DOCKER_USER}}/${{env.DOCKER_REPO}}:${{env.TAG_NAME}}

  TAG_gcc-arm:
    runs-on: ubuntu-20.04
    env:
      TAG_NAME: gcc-arm
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build image ${{env.DOCKER_REPO}}:${{env.TAG_NAME}}
      run: docker build ${{env.DOCKER_REPO}}/${{env.TAG_NAME}}/ --tag ${{env.DOCKER_REPO}}:${{env.TAG_NAME}}
    - name: Log in Docker Hub
      uses: docker/login-action@v1
      with:
        username: {{env.DOCKER_USER}}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push image tag <${{env.TAG_NAME}}> to remote
      run: |
        docker tag ${{env.DOCKER_REPO}}:${{env.TAG_NAME}} {{env.DOCKER_USER}}/${{env.DOCKER_REPO}}:${{env.TAG_NAME}}
        docker push {{env.DOCKER_USER}}/${{env.DOCKER_REPO}}:${{env.TAG_NAME}}


  TAG_armc6:
    runs-on: ubuntu-20.04
    env:
      TAG_NAME: armc6
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build image ${{env.DOCKER_REPO}}:${{env.TAG_NAME}}
      run: docker build ${{env.DOCKER_REPO}}/${{env.TAG_NAME}}/ --tag ${{env.DOCKER_REPO}}:${{env.TAG_NAME}}
    - name: Log in Docker Hub
      uses: docker/login-action@v1
      with:
        username: {{env.DOCKER_USER}}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push image tag <${{env.TAG_NAME}}> to remote
      run: |
        docker tag ${{env.DOCKER_REPO}}:${{env.TAG_NAME}} {{env.DOCKER_USER}}/${{env.DOCKER_REPO}}:${{env.TAG_NAME}}
        docker push {{env.DOCKER_USER}}/${{env.DOCKER_REPO}}:${{env.TAG_NAME}}
