# Copyright (c) 2021 Arm Limited
# SPDX-License-Identifier: Apache-2.0

name: PR Check [ ci-build-env ]
  
on:
  pull_request:
    branches: [ main ]

env:
  DOCKER_REPO: ci-build-env

jobs:

  TAG_sanity:
    runs-on: ubuntu-20.04
    env:
      TAG_NAME: sanity
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Docker image ${{env.DOCKER_REPO}}:${{env.TAG_NAME}}
      run: docker build ${{env.DOCKER_REPO}}/${{env.TAG_NAME}}/ --tag ${{env.DOCKER_REPO}}:${{env.TAG_NAME}}
    - name: Show tools installed
      run: docker run --rm ${{env.DOCKER_REPO}}:${{env.TAG_NAME}} cat env_settings
    - name: Test docker image
      run: docker run --rm ${{env.DOCKER_REPO}}:${{env.TAG_NAME}} ./env_test.sh

  TAG_gcc-arm:
    runs-on: ubuntu-20.04
    env:
      TAG_NAME: gcc-arm
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Docker image ${{env.DOCKER_REPO}}:${{env.TAG_NAME}}
      run: docker build ${{env.DOCKER_REPO}}/${{env.TAG_NAME}}/ --tag ${{env.DOCKER_REPO}}:${{env.TAG_NAME}}
    - name: Show tools installed
      run: docker run --rm ${{env.DOCKER_REPO}}:${{env.TAG_NAME}} cat env_settings
    - name: Test docker image
      run: docker run --rm ${{env.DOCKER_REPO}}:${{env.TAG_NAME}} ./env_test.sh


  TAG_armc6:
    runs-on: ubuntu-20.04
    env:
      TAG_NAME: armc6
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Docker image ${{env.DOCKER_REPO}}:${{env.TAG_NAME}}
      run: docker build ${{env.DOCKER_REPO}}/${{env.TAG_NAME}}/ --tag ${{env.DOCKER_REPO}}:${{env.TAG_NAME}}
    - name: Show tools installed
      run: docker run --rm ${{env.DOCKER_REPO}}:${{env.TAG_NAME}} cat env_settings
    - name: Test docker image
      run: docker run --rm ${{env.DOCKER_REPO}}:${{env.TAG_NAME}} ./env_test.sh
